language: csharp
mono:
  - latest

solution: Aragas.Core.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore SystemInfoLibrary.sln
  
script:
  - xbuild /p:Configuration=Release SystemInfoLibrary.sln
  - xbuild /p:Configuration=Debug SystemInfoLibrary.sln

notifications:
  email:
    on_success: always
